"""Multi-hospital fleet catalog for the fleet indicator profile.

Lab profile continues to use catalogs.py (GEHQ sample systems only).
"""

from __future__ import annotations

from .models import SiteProfile, SystemProfile

MACHINE_TYPES = ("Internal", "Clinical", "Demo")

SITES: dict[str, SiteProfile] = {
    "gehq": SiteProfile(
        site_id="gehq",
        site_code="GEHQ",
        hospital="GE MEDICAL SYSTEMS GLOBAL HEADQUARTERS",
        customer="GE MEDICAL SYSTEMS GLOBAL HEADQUARTERS",
        city="USA Other",
        state="WI",
        country="United States of America",
        region="USCAN",
        zone="USA Other",
        zipcode="53188",
        latitude="42.996",
        longitude="-88.311",
        location="POINT (-88.3115 42.9962)",
        machine_type="Internal",
        log_type="Revo_RTS_Data",
    ),
    "mayo_rst": SiteProfile(
        site_id="mayo_rst",
        site_code="MAYO",
        hospital="Mayo Clinic Rochester",
        customer="Mayo Clinic",
        city="Rochester",
        state="MN",
        country="United States of America",
        region="USCAN",
        zone="Upper Midwest",
        zipcode="55905",
        latitude="44.022",
        longitude="-92.467",
        location="POINT (-92.4668 44.0225)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "massgen": SiteProfile(
        site_id="massgen",
        site_code="MGH",
        hospital="Massachusetts General Hospital",
        customer="Mass General Brigham",
        city="Boston",
        state="MA",
        country="United States of America",
        region="USCAN",
        zone="New England",
        zipcode="02114",
        latitude="42.363",
        longitude="-71.069",
        location="POINT (-71.0686 42.3626)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "cedars": SiteProfile(
        site_id="cedars",
        site_code="CSMC",
        hospital="Cedars-Sinai Medical Center",
        customer="Cedars-Sinai Health System",
        city="Los Angeles",
        state="CA",
        country="United States of America",
        region="USCAN",
        zone="West Coast",
        zipcode="90048",
        latitude="34.075",
        longitude="-118.380",
        location="POINT (-118.3804 34.0752)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "uhn_tor": SiteProfile(
        site_id="uhn_tor",
        site_code="UHN",
        hospital="University Health Network",
        customer="University Health Network",
        city="Toronto",
        state="ON",
        country="Canada",
        region="CANADA",
        zone="Ontario",
        zipcode="M5G 2C4",
        latitude="43.659",
        longitude="-79.388",
        location="POINT (-79.3877 43.6591)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "charite": SiteProfile(
        site_id="charite",
        site_code="CHAR",
        hospital="Charite – Universitaetsmedizin Berlin",
        customer="Charite Berlin",
        city="Berlin",
        state="BE",
        country="Germany",
        region="EMEA",
        zone="DACH",
        zipcode="10117",
        latitude="52.526",
        longitude="13.378",
        location="POINT (13.3777 52.5265)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    # Wave-2 synthetic sites
    "cleveland": SiteProfile(
        site_id="cleveland",
        site_code="CLE",
        hospital="Cleveland Clinic Main Campus",
        customer="Cleveland Clinic",
        city="Cleveland",
        state="OH",
        country="United States of America",
        region="USCAN",
        zone="Great Lakes",
        zipcode="44195",
        latitude="41.503",
        longitude="-81.620",
        location="POINT (-81.6200 41.5032)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "hopkins": SiteProfile(
        site_id="hopkins",
        site_code="JHH",
        hospital="Johns Hopkins Hospital",
        customer="Johns Hopkins Medicine",
        city="Baltimore",
        state="MD",
        country="United States of America",
        region="USCAN",
        zone="Mid-Atlantic",
        zipcode="21287",
        latitude="39.297",
        longitude="-76.593",
        location="POINT (-76.5929 39.2967)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "karolinska": SiteProfile(
        site_id="karolinska",
        site_code="KAR",
        hospital="Karolinska University Hospital",
        customer="Karolinska Universitetssjukhuset",
        city="Stockholm",
        state="AB",
        country="Sweden",
        region="EMEA",
        zone="Nordics",
        zipcode="171 76",
        latitude="59.350",
        longitude="18.033",
        location="POINT (18.0330 59.3500)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "sinai_ny": SiteProfile(
        site_id="sinai_ny",
        site_code="MSNY",
        hospital="Mount Sinai Hospital New York",
        customer="Mount Sinai Health System",
        city="New York",
        state="NY",
        country="United States of America",
        region="USCAN",
        zone="Northeast",
        zipcode="10029",
        latitude="40.790",
        longitude="-73.953",
        location="POINT (-73.9531 40.7900)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "stanford": SiteProfile(
        site_id="stanford",
        site_code="SHC",
        hospital="Stanford Health Care",
        customer="Stanford Medicine",
        city="Palo Alto",
        state="CA",
        country="United States of America",
        region="USCAN",
        zone="West Coast",
        zipcode="94305",
        latitude="37.434",
        longitude="-122.175",
        location="POINT (-122.1750 37.4337)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "gehq_west": SiteProfile(
        site_id="gehq_west",
        site_code="GEHW",
        hospital="GE HealthCare Waukesha Campus",
        customer="GE HealthCare",
        city="Waukesha",
        state="WI",
        country="United States of America",
        region="USCAN",
        zone="Upper Midwest",
        zipcode="53188",
        latitude="43.012",
        longitude="-88.237",
        location="POINT (-88.2370 43.0120)",
        machine_type="Internal",
        log_type="Revo_RTS_Data",
    ),
    # Wave-3 synthetic sites
    "ucla": SiteProfile(
        site_id="ucla",
        site_code="UCLA",
        hospital="UCLA Medical Center",
        customer="UCLA Health",
        city="Los Angeles",
        state="CA",
        country="United States of America",
        region="USCAN",
        zone="West Coast",
        zipcode="90095",
        latitude="34.066",
        longitude="-118.445",
        location="POINT (-118.4450 34.0660)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "northwestern": SiteProfile(
        site_id="northwestern",
        site_code="NMH",
        hospital="Northwestern Memorial Hospital",
        customer="Northwestern Medicine",
        city="Chicago",
        state="IL",
        country="United States of America",
        region="USCAN",
        zone="Great Lakes",
        zipcode="60611",
        latitude="41.895",
        longitude="-87.621",
        location="POINT (-87.6210 41.8950)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "duke": SiteProfile(
        site_id="duke",
        site_code="DUKE",
        hospital="Duke University Hospital",
        customer="Duke Health",
        city="Durham",
        state="NC",
        country="United States of America",
        region="USCAN",
        zone="Southeast",
        zipcode="27710",
        latitude="36.007",
        longitude="-78.939",
        location="POINT (-78.9390 36.0070)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "toronto_sickkids": SiteProfile(
        site_id="toronto_sickkids",
        site_code="SKH",
        hospital="The Hospital for Sick Children",
        customer="SickKids",
        city="Toronto",
        state="ON",
        country="Canada",
        region="CANADA",
        zone="Ontario",
        zipcode="M5G 1X8",
        latitude="43.657",
        longitude="-79.387",
        location="POINT (-79.3870 43.6570)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "ap_hp": SiteProfile(
        site_id="ap_hp",
        site_code="APHP",
        hospital="AP-HP Pitie-Salpetriere",
        customer="Assistance Publique – Hopitaux de Paris",
        city="Paris",
        state="IDF",
        country="France",
        region="EMEA",
        zone="France",
        zipcode="75013",
        latitude="48.837",
        longitude="2.363",
        location="POINT (2.3630 48.8370)",
        machine_type="Clinical",
        log_type="Revo_Site_Data",
    ),
    "gehq_east": SiteProfile(
        site_id="gehq_east",
        site_code="GEHE",
        hospital="GE HealthCare Florence Campus",
        customer="GE HealthCare",
        city="Florence",
        state="SC",
        country="United States of America",
        region="USCAN",
        zone="Southeast",
        zipcode="29501",
        latitude="34.195",
        longitude="-79.763",
        location="POINT (-79.7630 34.1950)",
        machine_type="Internal",
        log_type="Revo_RTS_Data",
    ),
}

# Relative volume when sampling sites.
SITE_WEIGHTS: dict[str, float] = {
    "gehq": 1.0,
    "mayo_rst": 2.5,
    "massgen": 2.2,
    "cedars": 1.8,
    "uhn_tor": 1.5,
    "charite": 1.2,
    "cleveland": 2.0,
    "hopkins": 1.9,
    "karolinska": 1.4,
    "sinai_ny": 1.7,
    "stanford": 1.6,
    "gehq_west": 1.1,
    "ucla": 1.8,
    "northwestern": 1.7,
    "duke": 1.6,
    "toronto_sickkids": 1.3,
    "ap_hp": 1.5,
    "gehq_east": 1.0,
}

SYSTEMS: dict[str, SystemProfile] = {
    # GEHQ — Internal lab (sample-aligned)
    "CTBAY47": SystemProfile(
        sysid="CTBAY47",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.54",
        site_id="gehq",
        machine_type="Internal",
    ),
    "CTBAY52WSO": SystemProfile(
        sysid="CTBAY52WSO",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.50",
        site_id="gehq",
        machine_type="Internal",
    ),
    # Mayo
    "CTMNR01": SystemProfile(
        sysid="CTMNR01",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="mayo_rst",
        machine_type="Clinical",
    ),
    "CTMNR02": SystemProfile(
        sysid="CTMNR02",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.52",
        site_id="mayo_rst",
        machine_type="Clinical",
    ),
    # Mass General
    "CTMGH11": SystemProfile(
        sysid="CTMGH11",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="massgen",
        machine_type="Clinical",
    ),
    "CTMGH12": SystemProfile(
        sysid="CTMGH12",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW27.33",
        site_id="massgen",
        machine_type="Clinical",
    ),
    # Cedars
    "CTCSM21": SystemProfile(
        sysid="CTCSM21",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.52",
        site_id="cedars",
        machine_type="Clinical",
    ),
    "CTCSM22D": SystemProfile(
        sysid="CTCSM22D",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="24MW10.61",
        site_id="cedars",
        machine_type="Demo",
    ),
    # UHN Toronto
    "CTUHN31": SystemProfile(
        sysid="CTUHN31",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.50",
        site_id="uhn_tor",
        machine_type="Clinical",
    ),
    "CTUHN32": SystemProfile(
        sysid="CTUHN32",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.54",
        site_id="uhn_tor",
        machine_type="Clinical",
    ),
    # Charité
    "CTCHA41": SystemProfile(
        sysid="CTCHA41",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="charite",
        machine_type="Clinical",
    ),
    "CTCHA42D": SystemProfile(
        sysid="CTCHA42D",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.52",
        site_id="charite",
        machine_type="Demo",
    ),
    # Wave-2 systems (new hospitals → new sysids)
    "CTCLE51": SystemProfile(
        sysid="CTCLE51",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="cleveland",
        machine_type="Clinical",
    ),
    "CTCLE52": SystemProfile(
        sysid="CTCLE52",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.52",
        site_id="cleveland",
        machine_type="Clinical",
    ),
    "CTJHH61": SystemProfile(
        sysid="CTJHH61",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.50",
        site_id="hopkins",
        machine_type="Clinical",
    ),
    "CTJHH62D": SystemProfile(
        sysid="CTJHH62D",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW27.33",
        site_id="hopkins",
        machine_type="Demo",
    ),
    "CTKAR71": SystemProfile(
        sysid="CTKAR71",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="karolinska",
        machine_type="Clinical",
    ),
    "CTKAR72": SystemProfile(
        sysid="CTKAR72",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.52",
        site_id="karolinska",
        machine_type="Clinical",
    ),
    "CTMSN81": SystemProfile(
        sysid="CTMSN81",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="sinai_ny",
        machine_type="Clinical",
    ),
    "CTMSN82D": SystemProfile(
        sysid="CTMSN82D",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="24MW10.61",
        site_id="sinai_ny",
        machine_type="Demo",
    ),
    "CTSHC91": SystemProfile(
        sysid="CTSHC91",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.52",
        site_id="stanford",
        machine_type="Clinical",
    ),
    "CTSHC92": SystemProfile(
        sysid="CTSHC92",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.54",
        site_id="stanford",
        machine_type="Clinical",
    ),
    "CTGHW01": SystemProfile(
        sysid="CTGHW01",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="gehq_west",
        machine_type="Internal",
    ),
    "CTGHW02": SystemProfile(
        sysid="CTGHW02",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.50",
        site_id="gehq_west",
        machine_type="Internal",
    ),
    # Wave-3 systems (new hospitals → new sysids)
    "CTUCLA01": SystemProfile(
        sysid="CTUCLA01",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="ucla",
        machine_type="Clinical",
    ),
    "CTUCLA02": SystemProfile(
        sysid="CTUCLA02",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.52",
        site_id="ucla",
        machine_type="Clinical",
    ),
    "CTNMH01": SystemProfile(
        sysid="CTNMH01",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.50",
        site_id="northwestern",
        machine_type="Clinical",
    ),
    "CTNMH02D": SystemProfile(
        sysid="CTNMH02D",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW27.33",
        site_id="northwestern",
        machine_type="Demo",
    ),
    "CTDUKE01": SystemProfile(
        sysid="CTDUKE01",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="duke",
        machine_type="Clinical",
    ),
    "CTDUKE02": SystemProfile(
        sysid="CTDUKE02",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.52",
        site_id="duke",
        machine_type="Clinical",
    ),
    "CTSKH01": SystemProfile(
        sysid="CTSKH01",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="toronto_sickkids",
        machine_type="Clinical",
    ),
    "CTSKH02D": SystemProfile(
        sysid="CTSKH02D",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="24MW10.61",
        site_id="toronto_sickkids",
        machine_type="Demo",
    ),
    "CTAPHP01": SystemProfile(
        sysid="CTAPHP01",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.52",
        site_id="ap_hp",
        machine_type="Clinical",
    ),
    "CTAPHP02": SystemProfile(
        sysid="CTAPHP02",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.54",
        site_id="ap_hp",
        machine_type="Clinical",
    ),
    "CTGHE01": SystemProfile(
        sysid="CTGHE01",
        product_name="Revolution CT (Rev 160)",
        systype="Revolution CT",
        sw_version="25MW38.54",
        site_id="gehq_east",
        machine_type="Internal",
    ),
    "CTGHE02": SystemProfile(
        sysid="CTGHE02",
        product_name="Revolution Apex Elite (160)",
        systype="Revolution Apex",
        sw_version="25MW38.50",
        site_id="gehq_east",
        machine_type="Internal",
    ),
}

SYSTEM_WEIGHTS: dict[str, float] = {
    "CTBAY47": 1.0,
    "CTBAY52WSO": 1.2,
    "CTMNR01": 2.0,
    "CTMNR02": 1.6,
    "CTMGH11": 1.8,
    "CTMGH12": 1.5,
    "CTCSM21": 1.4,
    "CTCSM22D": 1.0,
    "CTUHN31": 1.3,
    "CTUHN32": 1.1,
    "CTCHA41": 1.2,
    "CTCHA42D": 0.9,
    "CTCLE51": 1.8,
    "CTCLE52": 1.5,
    "CTJHH61": 1.7,
    "CTJHH62D": 0.8,
    "CTKAR71": 1.4,
    "CTKAR72": 1.2,
    "CTMSN81": 1.6,
    "CTMSN82D": 0.9,
    "CTSHC91": 1.5,
    "CTSHC92": 1.3,
    "CTGHW01": 1.1,
    "CTGHW02": 1.0,
    "CTUCLA01": 1.7,
    "CTUCLA02": 1.4,
    "CTNMH01": 1.6,
    "CTNMH02D": 0.8,
    "CTDUKE01": 1.5,
    "CTDUKE02": 1.3,
    "CTSKH01": 1.2,
    "CTSKH02D": 0.7,
    "CTAPHP01": 1.4,
    "CTAPHP02": 1.2,
    "CTGHE01": 1.0,
    "CTGHE02": 0.9,
}

# Convenience: wave-2 / wave-3 hospital site_ids only.
WAVE2_SITE_IDS = (
    "cleveland",
    "hopkins",
    "karolinska",
    "sinai_ny",
    "stanford",
    "gehq_west",
)

WAVE3_SITE_IDS = (
    "ucla",
    "northwestern",
    "duke",
    "toronto_sickkids",
    "ap_hp",
    "gehq_east",
)


def systems_for(
    *,
    site_ids: list[str] | None = None,
    machine_types: list[str] | None = None,
    sysids: list[str] | None = None,
) -> dict[str, SystemProfile]:
    """Filter fleet systems by site / machine_type / sysid."""
    out: dict[str, SystemProfile] = {}
    for sysid, system in SYSTEMS.items():
        if sysids is not None and sysid not in sysids:
            continue
        if site_ids is not None and system.site_id not in site_ids:
            continue
        if machine_types is not None and system.machine_type not in machine_types:
            continue
        out[sysid] = system
    return out
